INDIGO_WELCOME_MESSAGE: "“Anyone who stops learning is old, whether at twenty or eighty. Anyone who keeps learning stays young.” -Henry Ford"
INDIGO_PRIMARY_COLOR: "#808080" # gray

# Footer links are dictionaries with a "title" and "url"
# To remove all links, write:
# INDIGO_FOOTER_NAV_LINKS: []
# INDIGO_FOOTER_LEGAL_LINKS: []
INDIGO_FOOTER_NAV_LINKS:
  - title: "About"
    url: "/about"
  - title: "Contact"
    url: "/contact"
INDIGO_FOOTER_LEGAL_LINKS:
    - title: "Terms of service"
      url: "/tos"
    - title: "Honor Code"
      url: "/honor"
    - title: "Privacy"
      url: "/privacy"
    - title: "Indigo Theme"
      url: "https://github.com/overhangio/indigo"
